import { IComprobanteDetail, IReceptor } from ".";

export interface IComprobanteMaster{
    id?: Number;
    tipo_comprobante: string;
    numeracion_comprobante?: string;
    fecha_emision: Date;
    tipo_moneda?: string;
    tipo_operacion?: string;
    tipo_nota?: string;
    tipo_documento_afectado?: string;
    fecha_documento_afectado?: Date;
    numeracion_documento_afectado?: string;
    motivo_documento_afectado?: string;
    total_gravadas: Number;
    total_igv: Number;
    total_venta: Number;
    monto_letras?: string;
    cadena_para_codigo_qr?: string;
    codigo_hash?: string;
    pdf_bytes?: string;
    url?: string;
    errors?: string;
    id_abastecimiento?: Number;
    pistola?: Number;
    codigo_combustible?: string;
    dec_combustible?: string;
    volumen?: Number;
    fecha_abastecimiento?: Date;
    tiempo_abastecimiento?: Number;
    volumen_tanque?: Number;
    comentario?: string;
    pago_tarjeta: Number;
    pago_efectivo: Number;
    pago_yape: Number;
    placa?: string;
    billete?: Number;
    producto_precio?: Number;
    ruc?: string;
    enviado?: Number;
    estado_nota_despacho?: Number;
    comprobante_nota_despacho?: string;
    fecha_facturado?: Date;
    cliente?    : Number;
    UsuarioId: Number;
    ReceptorId: Number;
    CierreTurnoId?: Number;
    items: IComprobanteDetail[];
}